name: Release
on:
  push:
    tags:
      - "v*"
env:
  GO_VERSION: stable

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            goos: linux
            goarch: amd64
            artifact: dist-linux/sample-linux-*.tar.gz
            compress: tar.gz
          - os: macos
            runner: macos-latest
            goos: darwin
            goarch: arm64
            artifact: dist-darwin/sample-darwin-*.tar.gz
            compress: tar.gz
          - os: windows
            runner: windows-latest
            goos: windows
            goarch: amd64
            artifact: dist-windows/sample-windows-*.zip
            compress: zip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make release
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.artifact }}

  release:
    name: Draft Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: g ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generate_release_notes: true
          files: |
            dist-linux/sample-linux-*.tar.gz
            dist-darwin/sample-darwin-*.tar.gz
            dist-windows/sample-windows-*.zip
