name: Release
on:
  push:
    tags:
      - "v*"
env:
  GO_VERSION: stable

jobs:
  build_for_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: make release
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-linux
          path: sample-linux-*.tar.gz

  build_for_macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        env:
          GOOS: darwin
          GOARCH: arm64
        run: make release
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-darwin
          path: sample-darwin-*.tar.gz

  build_for_windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Install build dependencies
        run: choco install zip
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        shell: bash
        env:
          GOOS: windows
          GOARCH: amd64
        run: make release
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-windows
          path: sample-windows-*.zip

  release:
    name: Draft Release
    needs:
      - build_for_linux
      - build_for_macos
      - build_for_windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: g ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generate_release_notes: true
          files: |
            dist-linux/sample-linux-*.tar.gz
            dist-darwin/sample-darwin-*.tar.gz
            dist-windows/sample-windows-*.zip
